{% set name = "websocket-client" %}
{% set snakename = "websocket_client" %}
{% set bundle = "tar.gz" %}
{% set version = "0.57.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ snakename }}/{{ snakename }}-{{ version }}.{{ bundle }}
  sha256: d735b91d6d1692a6a181f2a8c9e0238e5f6373356f561bb9dc4c7af36f452010

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  # Cannot be no-arch due to bytecode issues.

requirements:
  host:
    - python
    - pip

  run:
    - python
    - six

test:
  imports:
    - websocket
    - websocket.tests

about:
  home: https://github.com/liris/websocket-client
  license_file: LICENSE
  license: LGPL 2.1
  license_family: LGPL
  summary: 'WebSocket client for python. hybi13 is supported.'
  dev_url: https://github.com/liris/websocket-client

extra:
  recipe-maintainers:
    - pmlandwehr
    - scopatz
