{% set name = "websocket-client" %}
{% set snakename = "websocket_client" %}
{% set bundle = "tar.gz" %}
{% set version = "0.51.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "030bbfbf29ac9e315ffb207ed5ed42b6981b5038ea00d1e13b02b872cc95e8f6" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ snakename }}/{{ snakename }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python
    - pip

  run:
    - python
    - six

test:
  imports:
    - websocket
    - websocket.tests

about:
  home: https://github.com/liris/websocket-client
  license_file: LICENSE
  license: LGPL 2.1
  license_family: LGPL
  summary: 'WebSocket client for python. hybi13 is supported.'
  dev_url: https://github.com/liris/websocket-client

extra:
  recipe-maintainers:
    - pmlandwehr
    - scopatz
