{% set name = "websocket-client" %}
{% set snakename = "websocket_client" %}
{% set bundle = "tar.gz" %}
{% set version = "0.55.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "f6029deea21218f2c771848935aa26c15699c831770f4fa66958bdaabff80ca0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ snakename }}/{{ snakename }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  # Cannot be no-arch due to bytecode issues.

requirements:
  host:
    - python
    - pip

  run:
    - python
    - six

test:
  imports:
    - websocket
    - websocket.tests

about:
  home: https://github.com/liris/websocket-client
  license_file: LICENSE
  license: LGPL 2.1
  license_family: LGPL
  summary: 'WebSocket client for python. hybi13 is supported.'
  dev_url: https://github.com/liris/websocket-client

extra:
  recipe-maintainers:
    - pmlandwehr
    - scopatz
