{% set name = "websocket-client" %}
{% set snakename = "websocket_client" %}
{% set bundle = "tar.gz" %}
{% set version = "1.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ snakename }}/{{ snakename }}-{{ version }}.{{ bundle }}
  sha256: 3239df9f44da632f96012472805d40a23281a991027ce11d2f45a6f24ac4c3da

build:
  entry_points:
    - wsdump=websocket._wsdump:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - websocket
  commands:
    - pip check
    - wsdump --help
    - pytest --pyargs websocket.tests -v -r f
  requires:
    - pip
    - pytest

about:
  home: https://github.com/websocket-client/websocket-client
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: WebSocket client for Python
  description: |
    websocket-client is a WebSocket client for Python. It provides access to 
    low level APIs for WebSockets. websocket-client implements version hybi-13 
    of the WebSocket protocol. This client does not currently support the 
    permessage-deflate extension from RFC 7692.
  dev_url: https://github.com/websocket-client/websocket-client
  doc_url: https://github.com/websocket-client/websocket-client

extra:
  recipe-maintainers:
    - pmlandwehr
    - scopatz
