# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "sXn3UdItij/pUJF2zX7HKfMQIfoySv6cKdqMFquNaZOsAcMxcyg4wojTif+J+s3/ZSavRNvoMGy9vdf/1KA0/e9wEVqaAJr6QaBH8sxJdWmX4dPiab80iu6gh3ajUBivUHbyDv+AMOg5paIAUopyexQYOZPTxed3Rzpy1DS2i1JXkXcO0AIuy09t3HDyiuM0B2gD9iszemP5l1IeTxAbKU+dvGFe8w18ROLUAhAJ0iNLWTRRaCrNDLEijqlIwl1iINrQQUtZWOzlmHAljK2eJEEHr58xp2JX84gWn9g0niqj5SN4ovGS7P4VXyvSALkbY/EInDkAeqX8X8VkE6VZuKVWJ868+BnRqp0crKq3aZPyJkfqFzOOo0xAGKVx0CU7J+vPxFXPdzPMAewcY51Y3g7sjGswY/+09F9j14hgmjvBVbY5t5I34b3lTkU+WNLAlmuhS8KNsjglKyMydb553ttBA1XVkFhjbSjOPuf57Q8HU+4gsLEYqafIfjkr0jZ1P6kZw5kTv0+alPNw0KD++Yvahm699vi46smNzoC3g0MEwjdVR7ruNWzK5bDOKY/KCBGCbn0k/6P7G1Gh5P2bC722aNpBY5GLzrS6qf9+59CBZ9fas5qlW/+IaW+Jpt+Lk+PFEEVKYGxcMvuJSsWjSbE9625yDHzS5lP5heBErF4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
