travis:
  secure:
    BINSTAR_TOKEN: Ce7MA5YD1LvmcOl1Z2r5zJ5QnnYeQKptsb/sYlCQew96L2YFKET/bfrcr9hfgw5Tr36DTHgb6Y3D7iD9j16CWPWMOFynk1uMIL/Ri4MDfF8lgC+oeu2EiObYWWdL4o4xSKPmiaOPyvzj89gMOqCM/uhRHzjw42L2xycwDekxWpIstqTAXLjUKliT935DPIdSJuDFCFsZGN7qCv/wsm5NjmBen0tRbDDdZgMT/S/H+R1es4OgeetD4cQ/JM95Xo6rOom8/2Y4X0e1229MKhZhD7yK9bck4bEG9wU/FaOBGKuxWHlrmxi5w5u7BFtS0mBgpptY5FAC5QliE0SQ8FhBg3xagLBtvHX6PDCU4VIofthtInYYAkV1mkDFANkznkd3o3FbRNAxR15EcI/w195zUxdcq2RwuAZNgdMT0o+TATgL5+KqMXeEoHpewVrmQcnFQww/wwJZ4Wdtxmnck6oo9DPd9DSga8qutEhIjri04+T1HPo6BWI2xxymZRcnKLxwfgZQHKrpwDYCORrS2hot8jaVd6UKKUIaGt37UmSj8P9ogUXjVax1vs7oKS0oS8RtjL7qiwOU1u6ZTFW0dBh2DFKiu7t2eHMiQqbdj6nBD78v/1cWJ/XlfoMxVZ7Bc8719/z6zmQZyMbQ4lhoJ3i5bsAhRj4YOtKlR1tWgWX/aU8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
