travis:
  secure:
    BINSTAR_TOKEN: OqsB8tOyIzxTPqGXtk6kSiYZrs1LTl1JF4pXsKs9lDKzqfBn+mt/HtFgTmcyebkUQMmPQO3H4yeu15uzUL8WMVTt2hvZT4OZE1t8LAAm+sczl6VaTdFLZAJ0FBJ4rcV9IiWFIDU4+vEds3QcC734FMg4H4EgVZL7dg9GECVk4YQphKHr6BmXX7l1Gf19ksVqcnl3dpyGBRkT0Wh2G1kj1Gom/Ol7EdB/WNnat8FJOiD83lp7G63xKUWAr2qLg87y9+wzE7OoTJ5tUnotKaLKf4LBuGuAgCp1g3IWPuHs2awI6f3zxII3cMz1yoJ4FRpBFaoANuo7uHCrTESQaBZZC0/mNg4PA82yvJdwcz5tLmVfURZEibaVxua1SGxGXzbFMlvdLCav6uHHOfsVB7cFiWjZHwZpSFvLzxYBJRA8gQQDMmtXZ/98tYfePHrW62wQhDVg+oJVSv9dQf8S+NMXPoG6B9jmjd0LpcjI65t3f6iCFQiwZPGvJCgwvPlMB1ZhJB8rAdJVzuR7RbT6TDO9ctfc7xhPvTlk6PjHmYcIKOEKx3r8japXRQMsrYhNTnK+Jk/9KWR2DZuXy9utxNMOrBuI7GAEHyl7Pxz0ecabDzQEvSYcRgkehO/d8dpYGufD07xiNmLedpW/FTF1JFOuImOfGdKY29pCXvePyI0VPAM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
